import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  chronologicalSidebar: [
    {
      type: 'autogenerated',
      dirName: 'כרונולוגי',
    },
  ],

  thematicSidebar: [
    {
      type: 'autogenerated',
      dirName: 'תמטי',
    },
  ],
};

export default sidebars;
